<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FraudDetection.Domain\FraudDetection.Domain.csproj" />
    <ProjectReference Include="..\FraudDetection.Application\FraudDetection.Application.csproj" />
    <ProjectReference Include="..\FraudDetection.SharedKernel\FraudDetection.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
